FROM python:3.12.4-alpine3.20

RUN apk --no-cache add curl

WORKDIR /app

# copy dependencies to working dir
COPY requirements.txt . 

# install dependencies
RUN pip install -r requirements.txt

COPY * .

# Set environment variables for Flask
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=8080

# Expose the port the app runs on
EXPOSE 8080

# Start container using flask instead of a webserver
CMD [ "flask", "run"]